## Application controller
controller:
  metrics:
    enabled: true
dex:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
applicationSet:
  metrics:
    enabled: true
notifications:
  metrics:
    enabled: true
global:
    podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/cluster"
    prometheus.io/port: "9000"