apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-agent
  namespace: default
spec:
  destination:
    name: ''
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 0.10.0
    chart: grafana-agent
    helm:
      values: |
        fullnameOverride: metrics-agent
        agent:
          mode: 'static'
          configmap
            name: grafana-agent
            key: config
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true