apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ksm-kube-state-metrics
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 5.5.0
    chart: kube-state-metrics
    helm:
      values: |+

      parameters:
        - name: image.tag
          value: v2.8.2
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true